services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: snabik-api-debug
    entrypoint: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "-m", "app.main"]
    container_name: "api-debug"
    env_file:
      - ./envs/.env.dev.docker
    volumes:
      - /opt/huggingface:/app/hf
    ports:
    - 8001:8000
    - 5678:5678
    networks:
      - snabik
    environment:
      - PYTHONBUFFERED=1

networks:
  snabik:
    driver: bridge
    external: true
