services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: snabik-api
    entrypoint: ["python","-m" ,"app.main"]
    container_name: "api-prod"
    env_file:
      - ./envs/.env.prod.docker
    volumes:
      - /opt/huggingface:/app/hf
    ports:
    - 8000:8000
    - 5678:5678
    networks:
      - snabik

networks:
  snabik:
    driver: bridge
    external: true
